export const enum BLOCK_ACTIONS {
  CREATE_BLOCK = 'CREATE_BLOCK',
  UPDATE_BLOCK = 'UPDATE_BLOCK',
  DELETE_BLOCK = 'DELETE_BLOCK',
  DELETE_NOTE_BLOCKS = 'DELETE_NOTE_BLOCKS',
  REORDER_BLOCKS = 'REORDER_BLOCKS',
  MOVE_BLOCK = 'MOVE_BLOCK',
  SET_CURRENT_BLOCK = 'SET_CURRENT_BLOCK',
  CLEAR_CURRENT_BLOCK = 'CLEAR_CURRENT_BLOCK'
}
