export const enum BLOCK_ACTIONS {
  CREATE_BLOCK = 'CREATE_BLOCK',
  UPDATE_BLOCK = 'UPDATE_BLOCK',
  DELETE_BLOCK = 'DELETE_BLOCK',
  DELETE_NOTE_BLOCKS = 'DELETE_NOTE_BLOCKS',
  REORDER = 'REORDER',
  MOVE = 'MOVE'
}
